export const data1 = [
	{
		id: 1,
		img: './img/tf.svg',
		nameProduct: 'Tarta de fresa',
		description: 'Una deliciosa tarta de fresa',
		ingredients: 'Base de galleta sabor vainilla \nRelleno de fresa',
		category: 'Tartas',
		background: "#561215",
		price: 90,
		quantity: 1,
	},
	{
		id: 2,
		img: './img/tm.svg',
		nameProduct: 'Tarta de mora azul',
		description: 'Una tarta de mora azul con un toque de limón',
		ingredients: 'Base de galleta sabor vainilla \nRelleno de mora azul y limón',
		category: 'Tartas',
		background: "#171129",
		price: 100,
		quantity: 1,
	},
	{
		id: 3,
		img: './img/tp.svg',
		nameProduct: 'Tarta de piña',
		description: 'Una deliciosa tarta de piña',
		ingredients: 'Base de galleta sabor vainilla \nRelleno de piña',
		category: 'Tartas',
		background: "#B09E01",
		price: 30,
		quantity: 1,
	},
	{
		id: 1,
		img: './img/tp.svg',
		nameProduct: 'asdfasdf',
		description: 'sdf Nike para correr',
		ingredients: 'Suela de goma',
		category: 'Relojes',
	},
	{
		id: 2,
		img: './img/Logo.jpeg',
		nameProduct: 'JHolosdf',
		description: 'Zapatos Nike para correr',
		ingredients: 'Suela de goma',
		category: 'Relojes',
	},
];